### ISSUE TITLE
too high rank value

### ISSUE THREAD

**Issue by zunyun-Gong** [Freshwind-Bioinformatics/TABR-BERT#1]
Thank you for sharing your fasinating work. When I use it, I find all my TCR-pMHC get a very high rank which in your paper represent high possibility for binding. But, in our perspective it can be possible because there all both selected randomly from tumor T cell repertoire and neoantigens. Is there anything wrong?
<img width="977" alt="c7ee1d2c0a5f54e1b75cdf46cef2b95" src="https://github.com/Freshwind-Bioinformatics/TABR-BERT/assets/120580826/b2a2b2cf-5198-43b1-b2d2-330c4831e826">
code:singularity exec --pwd /mnt -c --bind /tools/TABR-BERT/:/mnt,/mydata/tabr/:/boot tabr-bert_v1.sif python /workspace/TABR-BERT/predict_tcr_pmhc_binding.py --input /boot/0t0_tabr.list --healthy_tcr ./data/small_healthy_tcr.csv --pseudo_sequence_dict ./data/mhcflurry.allele_sequences_homo.csv --output /boot/test.txt --GPUs 0

**Comment by JiaweiZhang1997** [comment]
This is possible because TABR-BERT returns a rank value, which suggests that the predicted TCRs have a higher probability of combining with the neoantigen relative to the TCRs in "healthy_tcr", and you might consider replacing "healthy_tcr" with your own set of TCRs to get more discriminatory results.

**Comment by zunyun-Gong** [comment]
Thank you for your answer! It helps me a lot.
